<?php 

//Could not get this function to work. Instead added it through the navigation setting
function contact_menu() {
	$items = array();
	$items['contact'] = array(
			'title' => 'Contact Form',
			'type' => MENU_NORMAL_ITEM,
			'access callback' => TRUE,
			'page callback' => 'drupal_get_form',
			'page arguments' => array('contact_form'),
		);

	return $items;
}



function contact_form() {
	$form = array();
	$form['your_name'] = array(
			'#title' => 'Your Name', 
			'#type' => 'textfield',
			'#description' => t('Please Enter Your Name.'),
		);

	$form['your_email'] = array(
			'#title' => 'Your Email', 
			'#type' => 'textfield',
			'#description' => t('Please Enter Your Email.'),
		);

	$form['subject'] = array(
			'#title' => 'Subject',
			'#type' => 'textfield',
			'#description' => t('Subject'),
		);

	$form['your_message'] = array(
			'#title' => 'Your Message',
			'#type' => 'textfield',
			'#description' => t('Write your message'),
		);

	$form['submit'] = array(
			'#type' => 'submit',
			'#value' => 'Submit',
		);


	return $form; 
}