<?php 

function contact_menu() {
	$items = array();
	$items['contact'] = array(
			'title' => 'Contact Form',
			'type' => MENU_NORMAL_ITEM, 
			'access callback' => TRUE, 
			'page callback' => 'drupal_get_form',
			'page arguments' => array('contact_form'),
		);
}

function contact_form() {
	$form = array();
	$form['your_name'] = array(
			'#title' => 'Your Name', 
			'#type' => 'textfield',
			'#description' => t('Please Enter Your Name.'),
		);

	$form['your_email'] = array(
			'#title' => 'Your Email', 
			'#type' => 'textfield',
			'#description' => t('Please Enter Your Email.'),
		);

	$form['subject']

	$form['your_message']


	return $form; 
}